language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    # Since PHP 8.0.0-dev is the new nightly, some dependencies don't support
    # it in their Composer files
    - php: nightly

    # https://github.com/php-vcr/php-vcr/issues/90
    - php: hhvm

    # Not 100% sure why this one is failing but we can get to it when 7.4-dev
    # becomes 7.4.0
    - php: 7.4snapshot

dist: trusty
sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer install --no-interaction --prefer-dist
  - composer show

script:
  - mkdir -p build/logs
  - composer test-coverage

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: false
  webhooks:
    - http://helit.org:8093/+sujevo-dev/showSuccessfulBuildMessages=always
